/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xhscnrprqokggtcbhwra"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhoc2NucnBycW9rZ2d0Y2Jod3JhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMTUxMzIsImV4cCI6MjA3ODU5MTEzMn0.ASsmCWtsGRviThE-9X5VPToCTuTD0wzSOeGk2F2--bA"